### PR TITLE
NUT11 sign outputs

### LINKED ISSUE #186: blindMessage not being signed
if I Create a token with nutstash that is P2PK. It will have SIG_ALL signaled in the inputs. 

At this moment the wallet is not signing the outputs and making the swap fail.
image

### PR DESCRIPTION
**Pull request by a1denvalu3**
# Fixes: [this issue](https://github.com/cashubtc/cashu.me/issues/186)

## Description
Adding support for signing the outputs when needed. This is a step towards `SIG_ALL` implementation and a fix for issues when trying to redeem `SIG_ALL` tokens on cashu.me and others that use cashu-ts behind the scenes. With this functionality we can then instruct cashu-ts to sign the outputs when it finds `SIG_ALL` tags.

## Changes

- added `signBlindedMessage`, `getSignedOutput`, `getSignedOutputs`
- introduced a new optional field `witness` in `BlindedMessage`
- modified `createRandomBlindedMessage` and `blindMessage` to allow a private key to be specified as input and act accordingly.
- npm run format

## PR Tasks

- [x] Open PR
- [x] run `npm run test` --> no failing unit tests
- [x] run `npm run format`

### CODE REVIEW

File: src/client/NUT11.ts [hunk 1]
```diff
@@ -23,6 +25,12 @@ export const signP2PKsecret = (secret: Uint8Array, privateKey: PrivKey) => {
 	return sig;
 };
 
+export const signBlindedMessage = (B_: string, privateKey: PrivKey) => {
```
Comment (gandlafbtc) [inline src/client/NUT11.ts]:
```suggestion
export const signBlindedMessage = (B_: string, privateKey: PrivKey): Uint8Array => {
```

File: src/mint/NUT11.ts [hunk 2]
```diff
@@ -42,3 +44,14 @@ export const verifyP2PKSig = (proof: Proof) => {
 		parsedSecret[1].data
 	);
 };
+
+export const verifyP2PKSigOutput = (output: BlindedMessage, publicKey: string) => {
```
Comment (gandlafbtc) [inline src/mint/NUT11.ts]:
```suggestion
export const verifyP2PKSigOutput = (output: BlindedMessage, publicKey: string): boolean => {
```

**Review by gandlafbtc — APPROVED** [review]
LGTM, 

Just added some suggestions for return types in method signatures
